#-----------------------------------------------------------------------
# INTRO
[[exercises]]
name = "intro1"
path = "exercises/01_intro/intro1.nr"
mode = "test"
hint = """
No hint needed
"""

#-----------------------------------------------------------------------
# VARIABLES
[[exercises]]
name = "variables1"
path = "exercises/02_variables/variables1.nr"
mode = "test"
hint = """
Declare the variable
"""

[[exercises]]
name = "variables2"
path = "exercises/02_variables/variables2.nr"
mode = "test"
hint = """
Add a value for the variable
"""

# OPERATIONS
[[exercises]]
name = "operations1"
path = "exercises/03_operations/operations1.nr"
mode = "test"
hint = """
Add a value for the variable
"""

[[exercises]]
name = "operations2"
path = "exercises/03_operations/operations2.nr"
mode = "test"
hint = """
Add a value for the variable
"""

# STRUCTS
[[exercises]]
name = "structs1"
path = "exercises/04_structs/structs1.nr"
mode = "test"
hint = """
Declare the variable
"""

[[exercises]]
name = "structs2"
path = "exercises/04_structs/structs2.nr"
mode = "test"
hint = """
"""
